import type {
  Contact,
  Message,
  Conversation,
  Campaign,
  Appointment,
  Notification,
  Order,
  Company,
  DashboardStats,
} from "@/types";

export const mockContacts: Contact[] = [
  {
    id: "c1",
    name: "Ahmet Yılmaz",
    phone: "+90 532 111 2233",
    email: "ahmet@sirket.com",
    avatar: "",
    company: "Yılmaz Teknoloji",
    tags: ["VIP", "Kurumsal"],
    source: "whatsapp",
    status: "customer",
    lastMessage: "Sipariş durumumu öğrenebilir miyim?",
    lastMessageTime: "2 dk önce",
    unreadCount: 3,
    assignedTo: "Mehmet A.",
    createdAt: "2024-01-15",
  },
  {
    id: "c2",
    name: "Fatma Demir",
    phone: "+90 505 222 3344",
    email: "fatma@gmail.com",
    avatar: "",
    tags: ["Yeni Lead"],
    source: "instagram",
    status: "lead",
    lastMessage: "Ürünleriniz hakkında bilgi almak istiyorum",
    lastMessageTime: "15 dk önce",
    unreadCount: 1,
    createdAt: "2024-03-10",
  },
  {
    id: "c3",
    name: "Mehmet Kaya",
    phone: "+90 542 333 4455",
    email: "mehmet.kaya@email.com",
    avatar: "",
    company: "Kaya İnşaat",
    tags: ["Kurumsal", "Premium"],
    source: "whatsapp",
    status: "customer",
    lastMessage: "Toplantı için uygun musunuz?",
    lastMessageTime: "1 saat önce",
    unreadCount: 0,
    assignedTo: "Ayşe B.",
    createdAt: "2024-02-20",
  },
  {
    id: "c4",
    name: "Ayşe Özkan",
    phone: "+90 533 444 5566",
    email: "ayse.ozkan@company.com",
    avatar: "",
    company: "Özkan Danışmanlık",
    tags: ["Potansiyel"],
    source: "telegram",
    status: "lead",
    lastMessage: "Fiyat listesini gönderebilir misiniz?",
    lastMessageTime: "3 saat önce",
    unreadCount: 2,
    createdAt: "2024-03-05",
  },
  {
    id: "c5",
    name: "Ali Çelik",
    phone: "+90 544 555 6677",
    email: "ali@celikgroup.com",
    avatar: "",
    company: "Çelik Group",
    tags: ["VIP", "Enterprise"],
    source: "email",
    status: "customer",
    lastMessage: "Sözleşme yenilemesi hakkında",
    lastMessageTime: "5 saat önce",
    unreadCount: 0,
    assignedTo: "Mehmet A.",
    createdAt: "2023-11-10",
  },
  {
    id: "c6",
    name: "Zeynep Arslan",
    phone: "+90 555 666 7788",
    email: "zeynep@arslanltd.com",
    avatar: "",
    company: "Arslan Ltd.",
    tags: ["Kurumsal"],
    source: "facebook",
    status: "active",
    lastMessage: "Demo talebimizi iletmek istiyoruz",
    lastMessageTime: "1 gün önce",
    unreadCount: 1,
    createdAt: "2024-03-01",
  },
  {
    id: "c7",
    name: "Emre Şahin",
    phone: "+90 506 777 8899",
    email: "emre.sahin@mail.com",
    avatar: "",
    tags: ["Bireysel"],
    source: "webchat",
    status: "active",
    lastMessage: "İade süreciniz nasıl işliyor?",
    lastMessageTime: "2 gün önce",
    unreadCount: 0,
    createdAt: "2024-03-12",
  },
  {
    id: "c8",
    name: "Elif Yıldız",
    phone: "+90 537 888 9900",
    email: "elif@yildizholding.com",
    avatar: "",
    company: "Yıldız Holding",
    tags: ["VIP", "Enterprise", "Premium"],
    source: "whatsapp",
    status: "customer",
    lastMessage: "Yıllık planımızı görüşelim",
    lastMessageTime: "3 gün önce",
    unreadCount: 0,
    assignedTo: "Ayşe B.",
    createdAt: "2023-09-15",
  },
];

export const mockMessages: Record<string, Message[]> = {
  c1: [
    {
      id: "m1",
      contactId: "c1",
      content: "Merhaba, sipariş durumumu öğrenebilir miyim?",
      type: "text",
      sender: "contact",
      channel: "whatsapp",
      timestamp: "10:30",
      status: "read",
    },
    {
      id: "m2",
      contactId: "c1",
      content: "Merhaba Ahmet Bey, sipariş numaranızı paylaşabilir misiniz?",
      type: "text",
      sender: "agent",
      channel: "whatsapp",
      timestamp: "10:32",
      status: "read",
    },
    {
      id: "m3",
      contactId: "c1",
      content: "SP-2024-0542 numaralı sipariş",
      type: "text",
      sender: "contact",
      channel: "whatsapp",
      timestamp: "10:33",
      status: "read",
    },
    {
      id: "m4",
      contactId: "c1",
      content:
        "Siparişiniz şu an kargoya verilmiş durumda. Tahmini teslimat tarihi: 15 Mart 2024. Kargo takip numaranız: TR123456789",
      type: "text",
      sender: "ai",
      channel: "whatsapp",
      timestamp: "10:33",
      status: "delivered",
      aiSuggestion: "Yapay zeka otomatik cevap verdi",
    },
    {
      id: "m5",
      contactId: "c1",
      content: "Teşekkür ederim, çok yardımcı oldunuz!",
      type: "text",
      sender: "contact",
      channel: "whatsapp",
      timestamp: "10:35",
      status: "read",
    },
    {
      id: "m6",
      contactId: "c1",
      content: "Rica ederiz! Başka bir sorunuz olursa her zaman yazabilirsiniz. 😊",
      type: "text",
      sender: "agent",
      channel: "whatsapp",
      timestamp: "10:36",
      status: "delivered",
    },
    {
      id: "m7",
      contactId: "c1",
      content: "Sipariş durumumu öğrenebilir miyim?",
      type: "text",
      sender: "contact",
      channel: "whatsapp",
      timestamp: "14:20",
      status: "read",
    },
  ],
  c2: [
    {
      id: "m8",
      contactId: "c2",
      content: "Merhaba, Instagram'daki ürünleriniz hakkında bilgi almak istiyorum",
      type: "text",
      sender: "contact",
      channel: "instagram",
      timestamp: "14:05",
      status: "read",
    },
    {
      id: "m9",
      contactId: "c2",
      content:
        "Merhaba! Hangi ürünümüz hakkında bilgi almak istersiniz? Size detaylı katalog gönderebiliriz.",
      type: "text",
      sender: "ai",
      channel: "instagram",
      timestamp: "14:05",
      status: "delivered",
      aiSuggestion: "Yapay zeka otomatik karşılama mesajı",
    },
    {
      id: "m10",
      contactId: "c2",
      content: "Ürünleriniz hakkında bilgi almak istiyorum",
      type: "text",
      sender: "contact",
      channel: "instagram",
      timestamp: "14:10",
      status: "read",
    },
  ],
  c4: [
    {
      id: "m11",
      contactId: "c4",
      content: "Fiyat listesini gönderebilir misiniz?",
      type: "text",
      sender: "contact",
      channel: "telegram",
      timestamp: "11:00",
      status: "read",
    },
    {
      id: "m12",
      contactId: "c4",
      content: "Tabii ki! Size güncel fiyat listemizi hemen gönderiyorum.",
      type: "text",
      sender: "agent",
      channel: "telegram",
      timestamp: "11:05",
      status: "delivered",
    },
  ],
};

export const mockConversations: Conversation[] = mockContacts
  .filter((c) => c.lastMessage)
  .map((contact) => ({
    id: `conv-${contact.id}`,
    contact,
    messages: mockMessages[contact.id] || [],
    channel: contact.source,
    status: contact.unreadCount > 0 ? ("open" as const) : ("resolved" as const),
    assignedTo: contact.assignedTo,
    priority: contact.tags.includes("VIP") ? ("high" as const) : ("medium" as const),
    lastActivity: contact.lastMessageTime || "",
  }));

export const mockCampaigns: Campaign[] = [
  {
    id: "camp1",
    name: "Bahar Kampanyası 2024",
    description: "Tüm ürünlerde %20 indirim kampanyası",
    type: "broadcast",
    channel: "whatsapp",
    status: "active",
    targetAudience: "Tüm Müşteriler",
    sentCount: 1250,
    deliveredCount: 1180,
    readCount: 890,
    responseCount: 156,
    createdAt: "2024-03-01",
  },
  {
    id: "camp2",
    name: "Yeni Ürün Lansmanı",
    description: "Premium ürün serisinin tanıtım kampanyası",
    type: "drip",
    channel: "email",
    status: "scheduled",
    targetAudience: "VIP Müşteriler",
    sentCount: 0,
    deliveredCount: 0,
    readCount: 0,
    responseCount: 0,
    scheduledAt: "2024-03-20",
    createdAt: "2024-03-10",
  },
  {
    id: "camp3",
    name: "Müşteri Memnuniyeti Anketi",
    description: "Aylık müşteri memnuniyeti değerlendirmesi",
    type: "broadcast",
    channel: "sms",
    status: "completed",
    targetAudience: "Aktif Müşteriler",
    sentCount: 500,
    deliveredCount: 485,
    readCount: 320,
    responseCount: 210,
    createdAt: "2024-02-15",
  },
  {
    id: "camp4",
    name: "Hoş Geldin Serisi",
    description: "Yeni kayıt olan müşteriler için otomatik karşılama mesajları",
    type: "triggered",
    channel: "whatsapp",
    status: "active",
    targetAudience: "Yeni Kayıtlar",
    sentCount: 340,
    deliveredCount: 335,
    readCount: 310,
    responseCount: 89,
    createdAt: "2024-01-01",
  },
  {
    id: "camp5",
    name: "Kış İndirimi",
    description: "Sezon sonu büyük indirim kampanyası",
    type: "promotional",
    channel: "instagram",
    status: "draft",
    targetAudience: "Tüm Takipçiler",
    sentCount: 0,
    deliveredCount: 0,
    readCount: 0,
    responseCount: 0,
    createdAt: "2024-03-12",
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: "apt1",
    contactId: "c1",
    contactName: "Ahmet Yılmaz",
    title: "Ürün Demo Toplantısı",
    description: "Premium paket tanıtımı",
    date: "2024-03-15",
    time: "10:00",
    duration: 60,
    status: "confirmed",
    type: "demo",
    assignedTo: "Mehmet A.",
    location: "Online - Zoom",
  },
  {
    id: "apt2",
    contactId: "c3",
    contactName: "Mehmet Kaya",
    title: "Sözleşme Görüşmesi",
    description: "Yıllık sözleşme yenileme",
    date: "2024-03-16",
    time: "14:00",
    duration: 45,
    status: "scheduled",
    type: "meeting",
    assignedTo: "Ayşe B.",
    location: "Ofis - Toplantı Odası 2",
  },
  {
    id: "apt3",
    contactId: "c5",
    contactName: "Ali Çelik",
    title: "Takip Görüşmesi",
    description: "Geçen ayki satış sonrası takip",
    date: "2024-03-14",
    time: "11:00",
    duration: 30,
    status: "completed",
    type: "follow_up",
    assignedTo: "Mehmet A.",
    notes: "Müşteri memnun, ek sipariş planlanıyor",
  },
  {
    id: "apt4",
    contactId: "c8",
    contactName: "Elif Yıldız",
    title: "Danışmanlık Seansı",
    description: "Dijital dönüşüm danışmanlığı",
    date: "2024-03-17",
    time: "09:00",
    duration: 90,
    status: "scheduled",
    type: "consultation",
    assignedTo: "Ayşe B.",
    location: "Online - Google Meet",
  },
  {
    id: "apt5",
    contactId: "c6",
    contactName: "Zeynep Arslan",
    title: "Telefon Görüşmesi",
    description: "İlk temas - ihtiyaç analizi",
    date: "2024-03-15",
    time: "16:00",
    duration: 20,
    status: "scheduled",
    type: "call",
    assignedTo: "Mehmet A.",
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "n1",
    title: "Yeni Mesaj",
    message: "Ahmet Yılmaz size WhatsApp'tan mesaj gönderdi",
    type: "message",
    read: false,
    timestamp: "2 dk önce",
    actionUrl: "/mesajlar",
  },
  {
    id: "n2",
    title: "Randevu Hatırlatma",
    message: "Yarın saat 10:00'da Ürün Demo Toplantısı var",
    type: "appointment",
    read: false,
    timestamp: "30 dk önce",
    actionUrl: "/randevular",
  },
  {
    id: "n3",
    title: "Kampanya Tamamlandı",
    message: "Bahar Kampanyası başarıyla tamamlandı. %71 açılma oranı!",
    type: "campaign",
    read: false,
    timestamp: "1 saat önce",
    actionUrl: "/kampanyalar",
  },
  {
    id: "n4",
    title: "Yapay Zeka Cevabı",
    message: "AI, Fatma Demir'in sorusuna otomatik cevap verdi",
    type: "ai",
    read: true,
    timestamp: "2 saat önce",
    actionUrl: "/mesajlar",
  },
  {
    id: "n5",
    title: "Yeni Sipariş",
    message: "Mehmet Kaya yeni bir sipariş oluşturdu - SP-2024-0589",
    type: "order",
    read: true,
    timestamp: "3 saat önce",
    actionUrl: "/kargo",
  },
  {
    id: "n6",
    title: "Sistem Güncellemesi",
    message: "Aizentr v2.1 güncellemesi yayınlandı",
    type: "system",
    read: true,
    timestamp: "1 gün önce",
  },
];

export const mockOrders: Order[] = [
  {
    id: "ord1",
    orderNumber: "SP-2024-0542",
    contactId: "c1",
    contactName: "Ahmet Yılmaz",
    products: [
      { name: "Premium Yazılım Lisansı", quantity: 5, price: 1200, sku: "LIC-PRE-001" },
      { name: "Kurulum Hizmeti", quantity: 1, price: 500, sku: "SRV-INS-001" },
    ],
    totalAmount: 6500,
    currency: "TRY",
    status: "shipped",
    trackingNumber: "TR123456789",
    carrier: "Aras Kargo",
    shippingAddress: "Atatürk Mah. 123. Sok. No:5 İstanbul",
    createdAt: "2024-03-10",
    updatedAt: "2024-03-12",
    estimatedDelivery: "2024-03-15",
  },
  {
    id: "ord2",
    orderNumber: "SP-2024-0589",
    contactId: "c3",
    contactName: "Mehmet Kaya",
    products: [
      { name: "Enterprise Paket", quantity: 1, price: 15000, sku: "PKG-ENT-001" },
    ],
    totalAmount: 15000,
    currency: "TRY",
    status: "confirmed",
    shippingAddress: "Cumhuriyet Blv. No:45 Ankara",
    createdAt: "2024-03-13",
    updatedAt: "2024-03-13",
  },
  {
    id: "ord3",
    orderNumber: "SP-2024-0510",
    contactId: "c5",
    contactName: "Ali Çelik",
    products: [
      { name: "Standart Lisans", quantity: 10, price: 800, sku: "LIC-STD-001" },
      { name: "Eğitim Paketi", quantity: 1, price: 2000, sku: "SRV-TRN-001" },
    ],
    totalAmount: 10000,
    currency: "TRY",
    status: "delivered",
    trackingNumber: "TR987654321",
    carrier: "Yurtiçi Kargo",
    shippingAddress: "Kızılay Mah. Ankara",
    createdAt: "2024-03-01",
    updatedAt: "2024-03-08",
  },
  {
    id: "ord4",
    orderNumber: "SP-2024-0601",
    contactId: "c8",
    contactName: "Elif Yıldız",
    products: [
      { name: "Enterprise Plus Paket", quantity: 1, price: 25000, sku: "PKG-ENTP-001" },
      { name: "7/24 Destek", quantity: 12, price: 1000, sku: "SRV-SUP-001" },
    ],
    totalAmount: 37000,
    currency: "TRY",
    status: "processing",
    shippingAddress: "Bağdat Cad. No:120 İstanbul",
    createdAt: "2024-03-14",
    updatedAt: "2024-03-14",
  },
  {
    id: "ord5",
    orderNumber: "SP-2024-0490",
    contactId: "c4",
    contactName: "Ayşe Özkan",
    products: [{ name: "Başlangıç Paketi", quantity: 1, price: 3500, sku: "PKG-STR-001" }],
    totalAmount: 3500,
    currency: "TRY",
    status: "pending",
    shippingAddress: "Konak Mah. İzmir",
    createdAt: "2024-03-14",
    updatedAt: "2024-03-14",
  },
];

export const mockCompany: Company = {
  id: "comp1",
  name: "Demo Şirket A.Ş.",
  phone: "+90 212 555 0000",
  email: "info@demosirket.com",
  website: "https://demosirket.com",
  address: "Levent Mah. İş Kuleleri No:1 İstanbul",
  industry: "Teknoloji",
  plan: "professional",
  connectedChannels: [
    { type: "whatsapp", identifier: "+90 532 000 1111", status: "connected", connectedAt: "2024-01-01" },
    { type: "instagram", identifier: "@demosirket", status: "connected", connectedAt: "2024-01-15" },
    { type: "telegram", identifier: "@demosirket_bot", status: "connected", connectedAt: "2024-02-01" },
    { type: "facebook", identifier: "Demo Şirket", status: "disconnected", connectedAt: "2024-02-10" },
    { type: "email", identifier: "destek@demosirket.com", status: "connected", connectedAt: "2024-01-01" },
  ],
  teamMembers: [
    { id: "tm1", name: "Mehmet Aydın", email: "mehmet@demosirket.com", role: "owner", avatar: "", status: "active" },
    { id: "tm2", name: "Ayşe Bulut", email: "ayse@demosirket.com", role: "admin", avatar: "", status: "active" },
    { id: "tm3", name: "Can Demir", email: "can@demosirket.com", role: "agent", avatar: "", status: "active" },
    { id: "tm4", name: "Selin Yılmaz", email: "selin@demosirket.com", role: "agent", avatar: "", status: "inactive" },
  ],
};

export const mockDashboardStats: DashboardStats = {
  totalConversations: 1284,
  activeConversations: 47,
  resolvedToday: 23,
  avgResponseTime: "2.4 dk",
  totalContacts: 3456,
  newContactsToday: 12,
  pendingAppointments: 8,
  activeCampaigns: 3,
  totalOrders: 156,
  revenue: 425000,
  aiResponseRate: 34,
  customerSatisfaction: 94,
};
